### ISSUE TITLE
Use Azure Active Directory as an external user store

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry-attic/login-server#54] opened 2015-08-26 09:31 UTC
Azure Active Directory supports SAML to enable SSO. And UAA also supports connecting to external user stores through LDAP and SAML. For SAML, my understanding is configuring a saml_login_server.
Does that mean I can integrate Azure AD with UAA and login-server just by changing configuration?
Thanks.

**Comment by fhanik** [comment] 2015-08-26 13:20
Closing - duplicate of https://github.com/cloudfoundry/uaa/issues/213

**Closed as completed by fhanik** 2015-08-26 13:20 UTC
